# -*- coding: utf-8 -*-
available_commentators = {
	'rashi' : {'xml_id' : '3', 'record' :{
		"title": 'Rashi',
		"titleVariants": ["Rashi"],
		"heTitle": 'רש"י',
        "heTitleVariants" :['רש"י'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'ramban' : {'xml_id' : '4', 'record' :{
		"title": 'Ramban',
		"titleVariants": ["Ramban", "Nachmanides",'Rabbi Moshe Ben Nachman'],
		"heTitle": 'רמב"ן',
        "heTitleVariants" :['רמב"ן'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'ibn ezra' : {'xml_id' : '5', 'record' :{
		"title": 'Ibn Ezra',
		"titleVariants": ['Ibn Ezra'],
		"heTitle": 'אבן עזרא',
        "heTitleVariants" :['אבן עזרא'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'sforno' : {'xml_id' : '6', 'record' :{
		"title": 'Sforno',
		"titleVariants": ['Sforno'],
		"heTitle": 'ספורנו',
        "heTitleVariants" :['ספורנו'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'baal haturim' : {'xml_id' : '7', 'record' :{
		"title": 'Kitzur Baal Haturim',
		"titleVariants": ['Kitzur Baal Haturim'],
		"heTitle": 'קיצור בעל הטורים',
        "heTitleVariants" :['קיצור בעל הטורים'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'or hachaim' : {'xml_id' : '8', 'record' :{
		"title": 'Or HaChaim',
		"titleVariants": ['Or Hachaim'],
		"heTitle": 'אור החיים',
        "heTitleVariants" :['אור החיים'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'siftei hachamim' : {'xml_id' : '28', 'record' :{
		"title": 'Ikar Siftei Hachamim',
		"titleVariants": ['Ikar Siftei Hachamim'],
		"heTitle": 'עיקר שפתי חכמים',
        "heTitleVariants" :['עיקר שפתי חכמים'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'kli yakar' : {'xml_id' : '29', 'record' :{
		"title": 'Kli Yakar',
		"titleVariants": ['Kli Yakar'],
		"heTitle": 'כלי יקר',
        "heTitleVariants" :['כלי יקר'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'torah temimah' : {'xml_id' : '9', 'record' :{
		"title": 'Torah Temimah',
		"titleVariants": ['Torah Temimah'],
		"heTitle": 'תורה תמימה',
        "heTitleVariants" :['תורה תמימה'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'metzudat david' : {'xml_id' : '10', 'record' :{
		"title": 'Metzudat David',
		"titleVariants": ['Metzudat David'],
		"heTitle": 'מצודת דוד',
        "heTitleVariants" :['מצודת דוד'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'metzudat zion' : {'xml_id' : '11', 'record' :{
		"title": 'Metzudat Zion',
		"titleVariants": ['Metzudat Zion'],
		"heTitle": 'מצודת ציון',
        "heTitleVariants" :['מצודת ציון'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'ralbag' : {'xml_id' : '12', 'record' :{
		"title": 'Ralbag',
		"titleVariants": ['Ralbag' ,'Gersonides'],
		"heTitle": 'רלב"ג',
        "heTitleVariants" :['רלב"ג'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'malbim' : {'xml_id' : '30', 'record' :{
		"title": 'Malbim',
		"titleVariants": ['Malbim', 'Malbim Literary Commantary'],
		"heTitle": 'מלבי"ם',
        "heTitleVariants" :['מלבי"ם'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},
    'malbim beur hamilot' : {'xml_id' : '31', 'record' :{
		"title": 'Malbim Beur Hamilot',
		"titleVariants": ['Malbim Beur Hamilot', 'Malbim Lexical Commentary'],
		"heTitle": 'מלבי"ם באור המילות',
        "heTitleVariants" :['מלבי"ם באור המילות'],
		"sectionNames": ["", ""],
		"categories": ['Commentary'],
	}},

}