# -*- coding: utf-8 -*-

import argparse
import django
django.setup()
from sefaria.model import *
from sefaria.clean import *
from sefaria.system.exceptions import InputError
from collections import *
import re
import csv
import pickle
import json
if __name__ == '__main__':
    broken_link_res = broken_links(auto_links=True,
                                   manual_links=True, delete_links=True,
                                   check_text_exists=True)
    with open("broken_links.csv", 'w') as f:
        writer = csv.writer(f)
        writer.writerow(["Ref 1", "Ref 2", "Generated By", "Problem with Link"])
        for link in broken_link_res:
            refs, generated_by, reason = link.split("\t")
            refs = eval(refs)
            writer.writerow([refs[0], refs[1], generated_by, reason])

