# Map masechet names to Sefaria ones

masechet_map = {'Berachot.': 'Mishnah Berakhot',
                'Peah.': 'Mishnah Peah',
                'Demai.': 'Mishnah Demai',
                'Kelaim.': 'Mishnah Kilayim',
                'Schebiit.': 'Mishnah Sheviit',
                'Terumoth.': 'Mishnah Terumot',
                'Maaseroth.': 'Mishnah Maasrot',
                'Maaser Scheni.': 'Mishnah Maaser Sheni',
                'Chalah.': 'Mishnah Challah',
                'Orlah.': 'Mishnah Orlah',
                'Bikkurim.': 'Mishnah Bikkurim',
                'Sabbath.': 'Mishnah Shabbat',
                'Erubin.': 'Mishnah Eruvin',
                'Pesachim.': 'Mishnah Pesachim',
                'SCHEKALIM.': 'Mishnah Shekalim',
                'Jom hak-Kippurim (Joma)': 'Mishnah Yoma',
                'SUKKA.': 'Mishnah Sukkah',
                'JOM TOB (B&#x00CA;SZA)': 'Mishnah Beitzah',
                'ROSCH HASCHANA.': 'Mishnah Rosh Hashanah',
                'TA&#x2018;ANIJOT.': "Mishnah Ta'anit",
                'M&#x2019;GILLA.': 'Mishnah Megillah',
                'MO&#x2018;ED &#x1E32;A&#x1E6C;AN.': 'Mishnah Moed Katan',
                '&#x2018;HAGIGA.': 'Mishnah Chagigah',
                'Jebamot.': 'Mishnah Yevamot',
                'Ketubot.': 'Mishnah Ketubot',
                'Nedarim.': 'Mishnah Nedarim',
                'Nasir.': 'Mishnah Nazir',
                'SOTA.': 'Mishnah Sotah',
                'GITTIN.': 'Mishnah Gittin',
                'KIDDUSCHIN.': 'Mishnah Kiddushin',
                'SEBACHIM.': 'Mishnah Zevachim',
                'MENACHOT.': 'Mishnah Menachot',
                'CHULLIN.': 'Mishnah Chullin',
                'BECHOROT.': 'Mishnah Bekhorot',
                'ARACHIN.': 'Mishnah Arakhin',
                'TEMURA.': 'Mishnah Temurah',
                'KERETOT': 'Mishnah Keritot',
                'ME&#x00CF;LA': 'Mishnah Meilah',
                'TAMID': 'Mishnah Tamid',
                'MIDDOT': 'Mishnah Middot',
                'KINNIM': 'Mishnah Kinnim',
                'KELIM.': 'Mishnah Kelim',
                'OHALOT.': 'Mishnah Oholot',
                'NEGA&#x00CF;M.': 'Mishnah Negaim',
                'PARA': 'Mishnah Parah',
                'TOHAROT.': 'Mishnah Tahorot',
                'MIKWAOT.': 'Mishnah Mikvaot',
                'NIDDA.': 'Mishnah Niddah',
                'MACHSCHIRIN.': 'Mishnah Makhshirin',
                'SABIM.': 'Mishnah Zavim',
                'TEBUL JOM.': 'Mishnah Tevul Yom',
                'JADAJIM.': 'Mishnah Yadayim',
                'UKZIN.': 'Mishnah Oktzin'}


def map_to_sefaria_masechet(de_masechet_name):
    return f"German Commentary on {masechet_map[de_masechet_name]}"
